### ISSUE TITLE
installing po and USER

### ISSUE THREAD

**Issue by knud** [nrobinson2000/po#1]
When installing po using

`bash <(curl -sL https://raw.githubusercontent.com/nrobinson2000/po/master/install)`

the process choked on a user name (USER) with a space under OS X, though I bet it's the same for Linux. Changing USER to be something without spaces fixed that problem. Not sure it warrants a change, but perhaps a warning or something?

**Comment by nrobinson2000** [comment]
Thanks for the heads up. I'll try to put a warning in.
