### ISSUE TITLE
[enhancement] Support for mesh family of devices

### ISSUE THREAD

**Issue by NGenetzky** [nrobinson2000/po#10]
Support is needed for new mesh devices

- boron
- xenon
- argon

You may want to warn the user if they are not using a `v0.8.0` or later tag (specifically `v0.8.0-rc.25-mesh`)

**Comment by nrobinson2000** [comment]
I've begun adding support for Mesh devices. So far you can build firmware for xenon, argon, and boron.

There are some steps required to set up po for mesh compilation that I have not automated **yet**.

```bash
po config v0.8.0-rc.25-mesh duo false
po update
cd ~/.po-util/src/particle/firmware
git submodule update --init
```

You'll want to re-source your `.bashrc` to get completion support.

After this, you should be able to `init` and `build` projects with xenon, argon and boron.

Example:

```bash
po xenon init mesh-test
cd mesh-test
po xenon build
```

I will get the other features like flashing and warnings worked out soon. I still haven't recieved my Mesh preorder yet.

**Note:**
I have not released this update on Homebrew yet, so mesh support is only on Linux at the moment.

**Comment by nrobinson2000** [comment]
I have released Mesh support on macOS. More updates will come soon but macOS is now up to speed with mesh support.

**Comment by dlarmitage** [comment]
upgrade went great.  I'll be testing tomorrow on both Xenon and Boron.  Thank you!
