### ISSUE TITLE
Include sources from a directory outside project structure

### ISSUE THREAD

**Issue by iamporus** [nrobinson2000/po#13]
My firmware depends upon a framework which resides in a different directory. This framework is generic and is needed by more such firmware.  Is there any way to include sources from that folder in build process?
Any help is much appreciated.
Thanks.

**Comment by nrobinson2000** [comment]
Have you tried including the files using the relative or absolute path?

Could you try something like?

```
#include "../../path/to/framework/framework.h"
```

**Comment by iamporus** [comment]
Thanks. I tried out the include path and it works as expected.
