### ISSUE TITLE
FLASHTOTAL/RAMTOTAL wrong for Argon, etc.?

### ISSUE THREAD

**Issue by larseggert** [nrobinson2000/po#16]
Aren't the `FLASHTOTAL` and `RAMTOTAL` numbers in
https://github.com/nrobinson2000/po/blob/306beebbc188ed3da2ccc9a18f6b5668a96bc507/share/po-common#L455-L456 incorrect for newer devices like the Argon? https://store.particle.io/products/argon says the Argon has "1MB flash, 256KB RAM".

Even for the Photon, https://store.particle.io/products/photon says "1MB flash, 128KB RAM". Or am I missing something?

**Comment by nrobinson2000** [comment]
Yeah the numbers aren’t very precise and are even less precise for the gen3 hardware.

Here is the original thread where I asked which numbers to use: https://community.particle.io/t/how-much-ram-and-flash-does-each-particle-device-have/36554?u=nrobinson2000
