### ISSUE TITLE
New LTS Particle Release (Particle OS v2.0.0) needs ARM toolchain v9.2.1 or later, but po util installs 5.3.1

### ISSUE THREAD

**Issue by macdonaldtomw** [nrobinson2000/po#22]
See screenshot:

![image](https://user-images.githubusercontent.com/6575957/102390419-c2cae880-3faa-11eb-9cf4-041213728dcf.png)

**Comment by nrobinson2000** [comment]
Hey @macdonaldtomw,

Thank you for your continued use of po-util.

This year, I stopped maintaining po-util and I now focus on neopo, a superior Python implementation of po-util that has better compatibility with official Particle tools.

I highly recommend switching to neopo for all future development. You will likely need to restructure projects that use the legacy po-util structure.

Website:
https://neopo.xyz

GitHub:
https://github.com/nrobinson2000/neopo

Man page:
https://neopo.xyz/docs/neopo.html
