### ISSUE TITLE
Allow devices to be skipped

### ISSUE THREAD

**Issue by robbielove** [nrobinson2000/po#4]
Could you please allow devices to be skipped if offline when doing multi ota updates

possibly with a cli switch like --skip-offline or just by default

**Comment by nrobinson2000** [comment]
This sounds like a great feature. I'll see if I can implement it.

**Comment by nrobinson2000** [comment]
I've implemented this feature. Offline devices are now skipped by default.

**Comment by robbielove** [comment]
This feature works perfectly, Thank you!!
