### ISSUE TITLE
Custom firmware

### ISSUE THREAD

**Issue by robbielove** [nrobinson2000/po#5]
Is is possible to allow custom selection of firmware such as a fork of the particle firmware?

I am interested in changing the USB device descriptor as suggested in this post 
[Can the USB device’s descriptor be changed](https://community.particle.io/t/can-the-usb-devices-descriptor-be-changed/38312)

However it would appear that the firmware needs to be forked to make the changes required, and then   for that forked firmware be used in po

Hopefully this forked firmware could be selected from a local or git server of my own instead of github

**Comment by nrobinson2000** [comment]
I've implemented this feature. To use custom firmware you can change the `PARTICLE_FIRMWARE_URL` in `~/.po-util/config` from `PARTICLE_FIRMWARE_URL=https://github.com/particle-iot/firmware.git` to whatever repo URL you want. The custom repo will be downloaded when you run `po install`.

**Comment by robbielove** [comment]
I have tried to test this and it appears it might work but unfortunately I ran into a lot of problems;

One of the problems I ran into was that po is expecting to use the .po-util/src/particle/firmware directory, my fork is in a directory called particle-firmware so it appears that I have just been flashing the one in the .po-util/src/particle/firmware directory as my fork appears to be in .po-util/src/particle/particle-firmware

I assume this might be the needed change:
`git clone "$PARTICLE_FIRMWARE_URL" firmware || ( cd firmware && git stash && git pull )` on po-mac line 71, so that the firmware is always cloned into the firmware directory instead of whatever it is named, and means that git clone wont work if src/particle/firmware is not empty ie. has original firmware.

Anyway, tried renaming the src/particle/particle-firmware to firmware and it rebuilt the firmware but did not seem to change on my device - it doesn't explicitly state the firmware is being rebuilt (which would be nice) but I know because warnings from a library I'm using, appear and then not every subsequent time.

However that could have happened because (another thing I need to understand) my device updated to particle 0.8.0-rc3 (unintentionally); does that mean any attempts to flash this 0.7.0 custom system firmware will be ignored as the device system firmware is already higher? (tried to downgrade but it keeps auto upgrading the bootloader back to force 0.8.0 to be applied again ><)

I wonder if you might know how to check if the custom firmware was actually flashed and is in use, if only a small part is changed by me - how will I know the firmware is mine and not just faulty or appearing to operate like unchanged firmware? are there any inbuilt ways you know of (like comparing a hash of what was flashed, if that can be done) or should I write code that will show me some sort of change - like print text via serial on startup 'custom firmware running'?

Hopefully then I can let you know it all worked :D

**Comment by robbielove** [comment]
Ok, so found I managed to downgrade to 0.7.0 and this required targeting the application to build against the 0.7.0 version of firmware which it was not doing - I had po download the firmware before I committed the custom changes and hence my branch was not visible and I assume it was using the previous one selected which in my case was stupidly 'develop', again putting my device back to 0.8.0-rc3 !!

I then figured out that po update would bring in the changes and again downgraded to 0.7.0 but this time only the application flashed (I assume since it was the same as before) and the version did not change - user firmware now correctly built against my custom branch (I verified by checking the files I affected in src/particle/firmware) on 0.7.0

I then used `po photon upgrade devicename` hoping it would change it but apparently this is a DFU only way of doing it, I tried it and this works but now I am lead to believe that the system firmware might only upgrade to a higher version and because it is already using 0.7.0 this doesn't trigger it to upgrade from particle to custom suggesting I may need to downgrade to 0.6.3 for it to 'auto/OTA' upgrade system firmware (or is DFU the only option for flashing custom firmware? or maybe it might require running my own particle server?)

I tried downgrading to 0.6.3 and found that despite using po after device was on 0.6.3 - it still got the 0.7.0 particle system firmware, so it seems this is something that is dictated by the firmware update apis and might have to be taken up with Particle. I'll close this for now since it works when using `po photon upgrade devicename`

**Comment by nrobinson2000** [comment]
@robbielove 
Thanks again for your interest in po-util.

I made the needed change a few days ago but I have yet to address your other observations.

Personally I'm still using 0.6.3 and will be until Particle fixes all the problems with 0.7.0 and 0.8.0.

As far as I know the upgrade process is not as straightforward with the newer versions as it is with 0.6.3.

I'll see if I can make `po DEVICE_TYPE build` more verbose like you've suggested.
